import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const html = readFileSync(new URL('./index.html', import.meta.url), 'utf8');
assert(html.includes('<html lang="ko">'), 'Korean document language missing');
const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(x => x[1]);
assert.equal(new Set(ids).size, ids.length, 'Duplicate id');
for (const [, id] of html.matchAll(/href="#([^"]+)"/g)) assert(ids.includes(id), `Broken anchor: #${id}`);
const chapters = [...html.matchAll(/<section class="chapter /g)];
assert(chapters.length >= 20 && chapters.length <= 35, 'Unexpected chapter count');
assert(html.includes('공개 자막'), 'Source coverage disclosure missing');
assert(html.includes('자동자막'), 'Transcript limitation missing');
assert(!html.includes('__REPOSITORY_URL__'), 'Unresolved template');
assert(!html.match(/\b(TODO|PLACEHOLDER|FIXME)\b/), 'Unfinished copy');
assert(!html.match(/<script[^>]+src=/), 'Unexpected external script dependency');
assert(html.includes('aria-live="polite"'), 'Navigation announcements missing');
const sources = [...html.matchAll(/href="(https:\/\/[^"\s]+)"/g)].map(x => x[1]);
assert(sources.length >= 25, 'Section-level sources missing');
for (const source of sources) assert(new URL(source).protocol === 'https:');
console.log(`SAIF seminar validated: ${chapters.length} chapters, ${ids.length} unique IDs, ${sources.length} source links`);
